name: .NET 5.0 Build

on:
  push:
    branches: [ Net50 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dotnet-setversion
      run: dotnet tool install -g dotnet-setversion

    - name: Choco install GitVersion.Portable
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install GitVersion.Portable

    - name: Run GitVersion
      run: gitversion /showvariable semver > sem.ver

    - name: Run SetVersion
      run: setversion -r "@sem.ver"

    - name: Build
      run: dotnet build --configuration Release --verbosity minimal

    - name: Test
      run: dotnet test --configuration Release --verbosity minimal

    - uses: actions/upload-artifact@v2
      with:
        name: nuget-artifacts
        path: /home/runner/work/SynchroFeed.Core/SynchroFeed.Core/nuget/Release/*.*nupkg
