name: .NET 5.0 Build

on:
  push:
    branches: [ Net50 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dotnet-setversion
      run: dotnet tool install -g dotnet-setversion

    - name: GitVersion
      id: gitversion  # step id used as reference for output values
      uses: roryprimrose/rungitversion@v1.0.0

    - name: SetVersion
      run: setversion -r ${{ steps.gitversion.outputs.SemVer }}

    - name: Build
      run: dotnet build --configuration Release --verbosity minimal

    - name: Test
      run: dotnet test --configuration Release --verbosity minimal

    - uses: actions/upload-artifact@v2
      with:
        name: nuget-artifacts
        path: ${GITHUB_WORKSPACE}/nuget/Release/*.*nupkg
