name: .NET 5.0 Build

on:
  push:
    branches: [ Net50 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Install dotnet-setversion
      run: dotnet tool install -g dotnet-setversion

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Run GitVersion
      run: dotnet-gitversion /showvariable semver > sem.ver 

    - name: SetVersion
      run: setversion -r "@sem.ver"

    - name: Build
      run: dotnet build --configuration Release --verbosity minimal

    - name: Test
      run: dotnet test --configuration Release --verbosity minimal

    - name: Echo GITHUB_WORKSPACE
      run: echo $GITHUB_WORKSPACE/nuget/Release/*.*nupkg
    - uses: actions/upload-artifact@v2
      with:
        name: nuget-artifacts
        path: ${{GITHUB_WORKSPACE}}/nuget/Release/*.*nupkg
